name: gcc1734
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
    - pip
    - pip:    
      - matplotlib
      - numpy
      - pandas
      - scikit-learn
      - scipy
      - seaborn
      - gymnasium
      - minisat
