name: gcc1734
channels:
  - conda-forge
dependencies:
- anaconda::matplotlib=3.6
- anaconda::numpy
- anaconda::pandas
- anaconda::python=3.11
- anaconda::scikit-learn
- anaconda::scipy
- anaconda::seaborn=0.12.0
