name: gcc1734
channels:
  - conda-forge
dependencies:
- anaconda::python
- anaconda::matplotlib
- anaconda::numpy
- anaconda::pandas
- anaconda::scikit-learn
- anaconda::scipy
- anaconda::seaborn
- anaconda::gymnasium
